name: Secure CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout code ---
      - name: Checkout
        uses: actions/checkout@v4

      # --- Python Setup ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flask pytest bandit safety checkov

      # --- Static Code Analysis (SAST) ---
      - name: Bandit Security Scan
        run: |
          echo "Running Bandit only on app.py..."
          bandit app.py

      # --- Unit Tests ---
      - name: Run Tests
        run: pytest -q

      # --- Dependency Vulnerability Scan ---
      - name: Safety Vulnerability Check
        run: safety check || true

      # --- Build Docker Image ---
      - name: Build Docker Image
        run: docker build -t secure-ci-demo .

      # --- Trivy Container Scan ---
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-ci-demo
          format: table
          exit-code: 1
          ignore-unfixed: true

      # --- Checkov IaC Scan (optional) ---
      - name: Checkov IaC Scan
        run: checkov -d infra || true
